# fly.toml app configuration file generated for bugtracker-draganmaksimovic on 2025-10-23T13:41:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bugtracker-draganmaksimovic'
primary_region = 'arn'

[build.args]
  NEXT_PUBLIC_API_URL = "https://bugtracker-backend-draganmaksimovic.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
